// Generated by CoffeeScript 1.6.3
(function() {
  var AQUESTALKPI, BOT_ID, KEYS, Twitter, exec, main, talk, talking;

  BOT_ID = "duxca";

  KEYS = require("./" + BOT_ID + "_key");

  AQUESTALKPI = "/home/pi/aquestalkpi/AquesTalkPi";

  Twitter = require("twitter");

  exec = require('child_process').exec;

  main = function() {
    var twit;
    twit = new Twitter(KEYS);
    return twit.stream("user", function(stream) {
      return stream.on("data", function(_arg) {
        var id_str, text, user;
        id_str = _arg.id_str, user = _arg.user, text = _arg.text;
        if (text != null) {
          return talk(text);
        }
      });
    });
  };

  talking = false;

  talk = function(text, cb) {
    if (cb == null) {
      cb = function() {};
    }
    if (talking) {
      return cb(false);
    }
    talking = true;
    return exec("" + AQUESTALKPI + " \"" + text + "\" | aplay", function(err, stdout, stderr) {
      talking = false;
      if (!err) {
        return cb();
      } else {
        console.log(err);
        console.log(err.code);
        return console.log(err.signal);
      }
    });
  };

  main();

}).call(this);
